/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/maps` | `/maps`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/misions` | `/misions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/perfil/editPerfil` | `/perfil/editPerfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(start)'}/welcome` | `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `${'/(start)'}/login/forgot` | `/login/forgot`; params?: Router.UnknownInputParams; } | { pathname: `${'/(start)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(start)'}/login/register` | `/login/register`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/maps` | `/maps`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/misions` | `/misions`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/perfil` | `/perfil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(home)'}/perfil/editPerfil` | `/perfil/editPerfil`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(start)'}/welcome` | `/welcome`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(start)'}/login/forgot` | `/login/forgot`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(start)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(start)'}/login/register` | `/login/register`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(home)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/maps${`?${string}` | `#${string}` | ''}` | `/maps${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/misions${`?${string}` | `#${string}` | ''}` | `/misions${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/perfil${`?${string}` | `#${string}` | ''}` | `/perfil${`?${string}` | `#${string}` | ''}` | `${'/(home)'}/perfil/editPerfil${`?${string}` | `#${string}` | ''}` | `/perfil/editPerfil${`?${string}` | `#${string}` | ''}` | `${'/(start)'}/welcome${`?${string}` | `#${string}` | ''}` | `/welcome${`?${string}` | `#${string}` | ''}` | `${'/(start)'}/login/forgot${`?${string}` | `#${string}` | ''}` | `/login/forgot${`?${string}` | `#${string}` | ''}` | `${'/(start)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `${'/(start)'}/login/register${`?${string}` | `#${string}` | ''}` | `/login/register${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/maps` | `/maps`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/misions` | `/misions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/perfil` | `/perfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(home)'}/perfil/editPerfil` | `/perfil/editPerfil`; params?: Router.UnknownInputParams; } | { pathname: `${'/(start)'}/welcome` | `/welcome`; params?: Router.UnknownInputParams; } | { pathname: `${'/(start)'}/login/forgot` | `/login/forgot`; params?: Router.UnknownInputParams; } | { pathname: `${'/(start)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `${'/(start)'}/login/register` | `/login/register`; params?: Router.UnknownInputParams; };
    }
  }
}
